### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by justinnitz**
## Description
Ran `npm audit fix` to resolve security findings. 

## Motivation and Context

Updates dependencies to reduce security findings.

## How Has This Been Tested?

Ran `npm test`. 

## Types of Changes

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Updated documentation (`README.md`, etc.) depending if the changes require it.

### CODE REVIEW

**Comment by justinnitz** [comment]
Would like more eyes on this. Also since the repo is open source, we should look at utilizing dependabot and other tools to autogenerate  security update PRs.

**Review by Dranith — APPROVED** [review]
Looks good.

**Review by stevelove — DISMISSED** [review]
:shipit:

**Review by bijujoseph — APPROVED** [review]
changes looks good

**Comment by bijujoseph** [comment]
@boristotle  - I am tagging you here because of the test failure. I believe @justinnitz change is failing because of ` "keyofStringsOnly": true` in tsconfig. You worked on that file last, can you review and suggest a fix. Thank you!  
https://github.com/CMSgov/qpp-shared-logger-node/blob/da330e9d1de83ee0f0cbcbebd2b0a84ddc2988d9/tsconfig.json#L18

**Review by boristotle — APPROVED** [review]

**Pull request merged**
